import Head from "next/head";
import "../styles/globals.scss";
import * as Layout from "../lib/components/layout/index";

function MyApp({ Component, pageProps }) {
  const bg="teal"
  return (
    <>
      <Head>
        <title>Next App Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://kit.fontawesome.com/a54ea23ea6.js" crossorigin="anonymous"></script> */}
      </Head>
      <div id="top-layout">
        {/* <Layout.Header /> */}
        <Layout.Nav color={bg} />
        <div id="page">
          <Component {...pageProps} />
        </div>
      </div>
      <Layout.Footer color={bg} />
    </>
  );
}

export default MyApp;
